//
//  films.swift
//  Flixster
//
//  Created by AJ Cardoza on 9/16/23.
//

import Foundation
import Nuke

struct Films {
    let title: String
    let shortOverview: String
    let overview: String
    let release_date: String
    let genre: String
    let runTime: String
    let poster_path: URL
    
}

extension Films {
    
    static var horrorFilms: [Films] = [
        Films(title: "Scream VI",
             shortOverview: "In the next installment, the survivors of the Ghostface killings leave Woodsboro behind and start a fresh chapter in New York City.",
            overview: "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter. In Scream VI, Melissa Barrera (Sam Carpenter), Jasmin Savoy Brown (Mindy Meeks-Martin), Mason Gooding (Chad Meeks-Martin), Jenna Ortega (Tara Carpenter), Hayden Panettiere (Kirby Reed) and Courteney Cox (Gale Weathers) return to their roles in the franchise alongside Jack Champion, Henry Czerny, Liana Liberato, Dermot Mulroney, Devyn Nekoda, Tony Revolori, Josh Segarra, and Samara Weaving.",
             release_date: "March 10, 2023",
             genre: "Horror Mystery Thriller",
             runTime: "2h 2m",
             poster_path: URL(string: "https://www.themoviedb.org/t/p/original/xjFmjCDxO5n1X04GyvT4lSL5W1L.jpg")!),
        Films(title: "Scream",
                    shortOverview: "25 years after a streak of brutal murders shocked the quiet town of Woodsboro, Calif., a new killer dons the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town's deadly past.",
                   overview: "Like the original movie 25 years ago, a teenage girl is at home alone when the phone rings. A man wants to play a game with her. With the threat of killing her best friend, Tara's forced to play along. She barely survives the ghost face masked intruder's stabbing. Her 5 year older sister, Sam(antha), who left home at 18 due to mental problems, Sam's boyfriend and Tara's high school friends visit her at the hospital. Later on in a bar, a guy provokes the friends and is later attacked outside in the parking lot by Ghostface. Sam receives a call from him at the hospital and then he unsuccessfully attacks her. She later reveals family secrets to her sister. Sam contacts one of the original victims, Dewey, for help. He warns two other original victims, Sidney Prescott and Gale Weathers, about Ghostface being back. Who is Ghostface? How many more must die?",
                    release_date: "Janury 14, 2022",
                    genre: "Horror Mystery Thriller",
                    runTime: "1h 54m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/nD4M4Bx457ryLuKYpxFwQ2IBJ5w.jpg")!),
       Films(title: "Scream 4",
                    shortOverview: "Ten years have passed, and Sidney Prescott, who has put herself back together thanks in part to her writing, is visited by the Ghostface Killer.",
                   overview: "Sidney Prescott, now the author of a self-help book, returns home to Woodsboro on the last stop of her book tour. There she reconnects with Sheriff Dewey and Gale, who are now married, as well as her cousin Jill and her Aunt Kate. Unfortunately, Sidney's appearance also brings about the return of Ghostface, putting Sidney, Gale, and Dewey, along with Jill, her friends, and the whole town of Woodsboro in danger.",
                    release_date: "April 15, 2011",
                    genre: "Horror Mystery Comedy",
                    runTime: "1h 51m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/7kjEHGXqIIMZ5EeNNEeZUP5ruIE.jpg")!),
       Films(title: "Scream 3",
                    shortOverview: "While Sidney and her friends visit the Hollywood set of Stab 3, the third film based on the Woodsboro murders, another Ghostface killer rises to terrorize them",
                   overview: "Sidney is hibernating in the woods, her whereabouts are unknown to everyone but Dewey. After a number of murders that seem to be related to the Woodsboro case take place on the set of Stab 3, Sid comes to Hollywood to be terrorized, find out more about her mother's death, and put together the final pieces of the Scream mystery.",
                    release_date: "February 4, 2000",
                    genre: "Horror Mystery",
                    runTime: "1h 56m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/qpH8ToZVlFD1bakL04LkEKodyDI.jpg")!),
       Films(title: "Scream 2",
                    shortOverview: "Two years after the first series of murders, as Sidney acclimates to college life, someone donning the Ghostface costume begins a new string of killings.",
                   overview: "It has been two years since the tragic events at Woodsboro. Sidney Prescott and Randy Meeks are trying to get on with their lives, and are currently both students at Windsor College. Cotton Weary is out of prison, and is trying to cash in on his unfortunate incarceration. Gale Weathers has written a bestseller (The Woodsboro Murders) which has been turned into the film (Stab) starring Tori Spelling as Sidney. As the film's play date approaches, the cycle of death begins anew. Dewey Riley immediately flies out of Woodsboro to try to protect Sidney. But in this sequel to the 1996 horror film, the number of suspects only goes down as the body count slowly goes up!",
                    release_date: "December 12, 1997",
                    genre: "Horror Mystery",
                    runTime: "2h",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/dORlVasiaDkJXTqt9bdH7nFNs6C.jpg")!),
       Films(title: "Scream",
                    shortOverview: "While Sidney and her friends visit the Hollywood set of Stab 3, the third film based on the Woodsboro murders, another Ghostface killer rises to terrorize them",
                   overview: "A year after her mother's death, Sidney Prescott (Neve Campbell) and her friends started experiencing some strange phone calls. They later learned the calls were coming from a crazed serial killer, in a white faced mask and a large black robe, looking for revenge. His phone calls usually consist of many questions, the main one being: What's your favorite scary movie? Along with much scary movie trivia, ending with bloody pieces of innocent lives scattered around the small town of Woodsboro.",
                    release_date: "December 20, 1996",
                    genre: "Horror Mystery",
                    runTime: "1h 51m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/aXAByjBN8UhaYvotqRCwa5MsMGu.jpg")!),
       Films(title: "Bride of Chucky",
                    shortOverview: "Chucky, the doll possessed by a serial killer, discovers the perfect mate to kill and revive into the body of another doll.",
                   overview: "Tiffany Valentine, a former lover and accomplice of serial killer Charles Lee Ray, bribes a police officer into giving her the dismembered parts of a children's doll-which Ray's soul inhabited-from an evidence locker before murdering him. Believing that Ray's soul still inhabits the doll, Tiffany stitches and staples Chucky back together and reenacts the voodoo ritual which had instilled Ray's soul inside the doll ten years prior.",
                    release_date: "October 16, 1998",
                    genre: "Horror Mystery Thriller",
                    runTime: "1h 29m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/pNGt3izpZXP6I21dg3ujSgiTnJu.jpg")!),
       Films(title: "Resident Evil: Death Island",
                    shortOverview: "A t-virus outbreak in San Francisco leads to Alcatraz Island, where a new evil has taken residence.",
                   overview: "D.S.O. agent Leon S. Kennedy is on a mission to rescue Dr. Antonio Taylor from kidnappers, when a mysterious woman thwarts his pursuit. Meanwhile, B.S.A.A. agent Chris Redfield is investigating a zombie outbreak in San Francisco, where the cause of the infection cannot be identified. The only thing the victims have in common is that they all visited Alcatraz Island recently. Following that clue, Chris and his team head to the island, where a new horror awaits them.",
                    release_date: "July 25, 2023",
                    genre: "Animation Action Adventure",
                    runTime: "1h 27m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/xzAQ28moSPEZxOHJ7WL1mX6hb5H.jpg")!),
       Films(title: "Saw X",
                    shortOverview: "The most chilling installment of the SAW franchise yet explores the untold chapter of Jigsaw's most personal game. ",
                   overview: "John Kramer (Tobin Bell) is back. The most chilling installment of the SAW franchise yet explores the untold chapter of Jigsaw's most personal game. Set between the events of SAW I and II, a sick and desperate John travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer - only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, John returns to his work, turning the tables on the con artists in his signature visceral way through a series of ingenious and terrifying traps. A Lionsgate release. Twisted Pictures presents, a Burg/Koules production.",
                    release_date: "September 29, 2023",
                    genre: "Horror Mystery Thriller",
                    runTime: "1h 58m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/hYaKxnvqQt4pMtFy5KptUYJo1S0.jpg")!),
       Films(title: "Critters",
                    shortOverview: "A group of small but vicious alien creatures called Crites escape from an alien prison transport vessel and land near a small farm town on earth, pursued by two shape-shifting bounty hunters.",
                   overview: "A Kansas farm is attacked by a hoard of hungry flesh-eating monsters from outer-space with razor sharp teeth and a witty attitude! The family who inhabit the farm must seek the help of a local drunk and his critter-fighting bounty hunting pals before its too late...",
                    release_date: "April 11, 1986",
                    genre: "Horror Comedy Sci-Fi",
                    runTime: "1h 26m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/7tFJqfcmu7sAxwcRwQ0j9qnGrok.jpg")!),
       Films(title: "A Nightmare on Elm Street",
                    shortOverview: "Teenager Nancy Thompson must uncover the dark truth concealed by her parents after she and her friends become targets of the spirit of a serial killer with a bladed glove in their dreams, in which if they die, it kills them in real life.",
                   overview: "Springwood County, Ohio. A deformed dream stalker has been tormenting high school student Nancy Thompson and the teenagers on Elm Street. But everyone knows nightmares are not real. The deep slashes on their bodies, however, say otherwise. And as innocents die left and right, ripped to pieces, the oneiric intruder's charred figure haunts Nancy, who must remain awake to stay alive. Now, bright-red blood and a long-forgotten, hair-raising connection to the small town blur the line between the victims' dreams and the ghastly murderer's realm. After all, the vengeful shadowy killer has all the time in the world to inflict pain. And sooner or later, the kids will fall asleep. Who can stand in hell's way and The Glove?",
                    release_date: "November 16, 1984",
                    genre: "Horror",
                    runTime: "1h 31m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/wGTpGGRMZmyFCcrY2YoxVTIBlli.jpg")!),
       Films(title: "A Nightmare on Elm Street",
                    shortOverview: "The spectre of a disfigured man haunts the children of the parents who murdered him, stalking and killing them in their dreams.",
                   overview: "Death stalks the dreams of several young adults to claim its revenge on the killing of Freddy Kruger. Chased and chastised by this finger-bladed demon, it is the awakening of old memories and the denials of a past of retribution that spurns this hellish vision of a dreamlike state and turns death into a nightmare reality.",
                    release_date: "April 30, 2010",
                    genre: "Horror Crime Drama",
                    runTime: "1h 35m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/nsmW28GcNabCUZfP5YtUEe8Li0f.jpg")!),
       Films(title: "Friday the 13th",
                    shortOverview: "A group of camp counselors trying to reopen a summer camp called Crystal Lake, which has a grim past, are stalked by a mysterious killer.",
                   overview: "In 1957, at Camp Crystal Lake, young Jason Voorhees drowned. In 1958, two camp counselors were murdered. In 1962, fires and bad water thwarted the camp's reopening. Now, in 1980, Steve Christy finally reopens Camp Crystal Lake with the help of a few new counselors, ignoring the warnings of a crazy old man. The murders start up again while a mysterious stalker prowls the area. Is the killer seeking revenge? Who will survive the nightmare and live to tell the story?",
                    release_date: "May 9, 1980",
                    genre: "Horror Mystery Thriller",
                    runTime: "1h 35m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/HzrPn1gEHWixfMOvOehOTlHROo.jpg")!),

       Films(title: "Friday the 13th",
                    shortOverview: "A group of young adults visit a boarded up campsite named Crystal Lake where they soon encounter the mysterious Jason Voorhees and his deadly intentions.",
                   overview: "A group of young adults set up tent near the abandoned summer camp where a series of gruesome murders are said to have taken place back in 1980. The perpetrator was a grieving mother, driven insane by the drowning of her child, Jason, whom she believed was neglected by the camp counselors. As legend has it, the last survivor of the attacks beheaded the woman. But then Jason came back, and now he is a vengeful and inexorable killer, wielding crossbows, swords, axes and other sharp instruments. The legend proves horribly true, as these campers quickly discover. Six weeks later, the brother of one of those campers distributes posters of his missing sister. The police believe she took off with her boyfriend; but he knows better. The brother crosses paths with an uptight young rich guy who is having his girlfriend and friends over at his parents' cabin. The brother ends up at the cabin himself just before his sister's attacker sets upon them all.",
                    release_date: "February 13, 2009",
                    genre: "Horror Mystery Thriller",
                    runTime: "1h 37m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/88wlJ4teYlck4hJ2bnlxBrAVh0m.jpg")!),
       Films(title: "Freddy vs. Jason",
                    shortOverview: "Freddy Krueger and Jason Voorhees return to terrorize the teenagers of Elm Street. Only this time, they're out to get each other, too.",
                   overview: "It's been nearly ten years since Freddy Krueger terrorized people in the dreams, and the towns folk want to keep him erased from their memory. Freddy still has one more plan on getting back to Elm Street. He resurrects Jason Voorhees and sends him off to kill. The more bodies which fall to the ground, the stronger in which Freddy becomes. This is until, Freddy realizes that Jason isn't going to step aside easily, and must be taken down himself.",
                    release_date: "August 15, 2003",
                    genre: "Horror Action",
                    runTime: "1h 37m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/fhnWQDd05qEqtvZFwCwzmnVZYQy.jpg")!),
       Films(title: "Alien",
                    shortOverview: "The crew of a commercial spacecraft encounters a deadly lifeform after investigating an unknown transmission.",
                   overview: "In the far reaches of space, the crew on board the ship 'Nostromo' is returning to Earth until it receives a distress call, an alien one. However, the crew will soon take back with it the most terrifying creature in the universe: a Xenomorph, a killing machine that bleeds corrosive acid whenever anyone tries to hurt it. All alone in space, no one can hear them scream - trying to warn the rest of the galaxy of the terror that is the Xenomorph.",
                    release_date: "June 22, 1979",
                    genre: "Horror Sci-Fi",
                    runTime: "1h 57m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/2g0KQm3DnbaP1W34kCqmiMpEmZA.jpg")!),
       Films(title: "Predator",
                    shortOverview: "A team of commandos on a mission in a Central American jungle find themselves hunted by an extraterrestrial warrior.",
                   overview: "Assigned to locate a Central American cabinet minister and eliminate the region's scattered guerrillas, battle-hardened Major Alan 'Dutch' Schaefer leads his hand-picked squad of elite commandos into the jungle. However, they are unaware that an unidentified interstellar spacecraft has landed near them. Now, an otherwise routine rescue mission turns into a bloodbath, as ritualistically mutilated bodies found at the scene give away only one thing: someone, or perhaps something, is hunting them for sport. When Dutch attempts to confront the extraterrestrial tracker with his combat experience, he discovers their primitive weapons are no match for the creature's state-of-the-art weaponry. Does the outgunned and outmatched squad stand a chance against the ultimate hunter, the Predator?",
                    release_date: "June 12, 1987",
                    genre: "Horror Action Adventure",
                    runTime: "1h 47m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/5aqkZJV3PVIAfbxPkCqCdQ3eJ6P.jpg")!),
       Films(title: "Alien vs. Predator",
                    shortOverview: "During an archaeological expedition on Bouvetøya Island in Antarctica, a team of archaeologists and other scientists find themselves caught up in a battle between the two legends. Soon, the team realize that only one species can win.",
                   overview: "After detecting heat emanating from an ancient pyramid buried deep within the ice caps of Antarctica, billionaire industrialist Charles Bishop Weyland and his scientific team arrive on the icy continent. At first, this unexpected discovery fascinates them. However, once they set foot in the complex network of cavernous chambers, the intruders realise this intricate construction is not the work of the human intellect. But then, the walls start to move, trapping the unsuspecting explorers. And as three young Predators enter the dark temple of adjudication for their rite of passage, aggressive endoparasitoid Xenomorphs, or Aliens (1986), start flocking into the ancient structure. Now, the humans find themselves caught in the middle of a brutal, centuries-old power struggle. Who will prevail in the ultimate battle between Aliens and Predators?",
                    release_date: "August 13, 2004",
                    genre: "Horror Action Adventure",
                    runTime: "1h 41m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/ySWu5bCnnmgV1cVacvFnFIhgOjp.jpg")!),
       Films(title: "Halloween",
                    shortOverview: "Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.",
                   overview: "October 31, 1963, Haddonfield, Illinois. Possessed by an unfathomable urge to kill, six-year-old Michael Myers butchers his fifteen-year-old sister, Judith, on the night of Halloween. Precisely fifteen long years later, on the anniversary of the brutal murder, Michael escapes from Smith's Grove Sanitarium, a mental health facility for the criminally insane, and returns home. And before long, Michael becomes fixated on blissfully unsuspecting high school student Laurie Strode and her friends, Annie and Lynda. In the meantime, Myers' psychiatrist, Dr Samuel Loomis, and sceptical Sheriff Leigh Brackett comb the town to ferret out the mentally unstable inmate. However, the shadows are thick, and the silent killer is always one step ahead of them. Has Michael Myers returned to pick up where he left off?",
                    release_date: "October 27, 1978",
                    genre: "Horror Thriller",
                    runTime: "1h 31m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/wijlZ3HaYMvlDTPqJoTCWKFkCPU.jpg")!),
       Films(title: "Halloween",
                    shortOverview: "Laurie Strode confronts her long-time foe, Michael Myers, the masked figure who has haunted her since she narrowly escaped his killing spree on Halloween night four decades ago.",
                   overview: "Still living in dread of having to face Michael, the person who destroyed her life, lucky survivor Laurie Strode has been bracing herself up for the past forty years for another encounter with the maniacal serial killer. And in 2018, four painful decades after the bloodbath in Haddonfield and the shocking events of Halloween (1978), her fears come true as Myers escapes from the custody of Dr Sartain in Smith's Grove Sanitarium. Now, Michael's butcher knife has the final say, and even though no one seems to believe in the existence of pure evil, Laurie is determined to stand up for herself and rid the town of the nightmare once and for all. But has Laurie what it takes to look evil in the eye and confront the Boogeyman?",
                    release_date: "October 19, 2018",
                    genre: "Horror Crime Thriller",
                    runTime: "1h 46m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/f7JAX5EGk4GgsEnus6OxyzwpFp7.jpg")!),
       Films(title: "Halloween Kills",
                    shortOverview: "Surviving victims of Michael Myers form a vigilante mob and vow to end his reign of terror.",
                   overview: "Minutes after Laurie Strode (Curtis), her daughter Karen (Judy Greer) and granddaughter Allyson (Andi Matichak) left masked monster Michael Myers caged and burning in Laurie's basement, Laurie is rushed to the hospital with life-threatening injuries, believing she finally killed her lifelong tormentor. But when Michael manages to free himself from Laurie's trap, his ritual bloodbath resumes. As Laurie fights her pain and prepares to defend herself against him, she inspires all of Haddonfield to rise up against their unstoppable monster. The Strode women join a group of other survivors of Michael's first rampage who decide to take matters into their own hands, forming a vigilante mob that sets out to hunt Michael down, once and for all. Evil dies tonight.",
                    release_date: "October 15, 2021",
                    genre: "Horror Action Thriller",
                    runTime: "1h 45m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/hi6bnCKquI4kVOuWtdZGIbC6ESQ.jpg")!),
       Films(title: "Halloween Ends",
                    shortOverview: "The saga of Michael Myers and Laurie Strode comes to a spine-chilling climax in the final installment of this trilogy.",
                   overview: "Four years after the events of last year's Halloween Kills, Laurie is living with her granddaughter Allyson and is finishing writing her memoir. Michael Myers hasn't been seen since. Laurie, after allowing the specter of Michael to determine and drive her reality for decades, has decided to liberate herself from fear and rage and embrace life. But when a young man, Corey Cunningham, is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can't control, once and for all.",
                    release_date: "October 14, 2022",
                    genre: "Horror Thriller",
                    runTime: "1h 51m",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/4TWCHSziUs6vhpUYVAjcIUXSWwv.jpg")!),
       Films(title: "Thanksgiving",
                    shortOverview: "After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the infamous holiday.",
                   overview: "After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the infamous holiday.",
                    release_date: "November 17, 2023",
                    genre: "Horror Mystery Thriller",
                    runTime: "Unknown",
                    poster_path: URL(string: "https://www.themoviedb.org/t/p/original/lhmdKoZciQsD6pOxIi0ZkXudISw.jpg")!)
    ]
    
}
